### ISSUE TITLE
URL failure

### ISSUE THREAD

**Issue by zhushk21** [uw-cmg/DefectSTEMVideoAnalysis#1]
Hi, When I tried your demo, I found that the original URL was invalid. I hope you can update it.

![image](https://github.com/user-attachments/assets/37181d4a-ea37-43ac-af3f-c1c0e1c52388)

In addition, the cudnn version of tensorflow1.12.0 (7.2.1) has been removed from NVIDIA. I hope I can get the installation package from you.

**Comment by iphyer** [comment]
Hi zhushk21,

The default path for Google Colab is `/content/drive` to read file in your own Google Drive. You shall upload the video into that file by yourself, check this Stackoverflow post for more information, [How to read data in Google Colab from my Google drive?](https://stackoverflow.com/questions/48376580/how-to-read-data-in-google-colab-from-my-google-drive). If you're not using Google Colab and running it locally, you’ll need to update the path to your local directory.

Unfortunately, we don't have specific `tensorflow` packages either; we install via pip in Google Colab. I suggest trying to search for the package online. However, I highly recommend using the latest version if possible, as it's been 6 years at least since the release, and significant advancements have been made, especially in AI infrastructure.
